version: "3.8"

services:
  web:
    image: php:7.4-apache
    container_name: php_apache
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    command: >
      bash -c "
      docker-php-ext-install mysqli pdo pdo_mysql &&
      a2enmod rewrite &&
      apache2-foreground
      "
    # user: "1000:1000"
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:5.2
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      # PMA_USER: root
      # PMA_PASSWORD: root
      PMA_PORT: 3306
      PMA_ARBITRARY: 0
    depends_on:
      - db

  cron:
    build:
      context: .
      dockerfile: cron/Dockerfile
    container_name: php_cron
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    restart: always

volumes:
  db_data:
